# .kodiak.toml
version = 1

[merge]
automerge_label = "pr: automerge"
require_automerge_label = true
delete_branch_on_merge = true

[update]
# https://kodiakhq.com/docs/config-reference#updatealways
# always "update" (i.e. merge main branch into PR), if it has the automerge_label.
# Without this, only branches that are passing CI will get updated.
# The benefit of this config is that PRs that we want to automerge, but
# have failed because the test suite is flaky will get stuck, unless someone
# presses the Update Branch button manually, or re-triggers the Github workflow
# for tests again. This causes delays in getting easy PRs in.
always = true
